spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
  refresh:
    expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:1209600000}
