-- Seed simples de livros de referência para recomendações locais
-- A ideia é manter um catálogo local com títulos clássicos, famosos e em alta.

INSERT INTO book_catalog (title, author, language, editorial_category, created_at, updated_at)
VALUES
    ('Dom Casmurro', 'Machado de Assis', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Harry Potter e a Pedra Filosofal', 'J. K. Rowling', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Biblioteca da Meia-Noite', 'Matt Haig', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Empregada', 'Freida McFadden', 'pt', 'TRENDING', NOW(), NOW()),
    ('Verity', 'Colleen Hoover', 'pt', 'TRENDING', NOW(), NOW()),
    ('It: A Coisa', 'Stephen King', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Orgulho e Preconceito', 'Jane Austen', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Hábitos Atômicos', 'James Clear', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Hora da Estrela', 'Clarice Lispector', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Senhor dos Anéis: A Sociedade do Anel', 'J. R. R. Tolkien', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Hobbit', 'J. R. R. Tolkien', 'pt', 'CLASSIC', NOW(), NOW()),
    ('As Duas Torres', 'J. R. R. Tolkien', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Retorno do Rei', 'J. R. R. Tolkien', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Harry Potter e a Câmara Secreta', 'J. K. Rowling', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Harry Potter e o Prisioneiro de Azkaban', 'J. K. Rowling', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Harry Potter e o Cálice de Fogo', 'J. K. Rowling', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Percy Jackson e o Mar de Monstros', 'Rick Riordan', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Nome do Vento', 'Patrick Rothfuss', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Temor do Sábio', 'Patrick Rothfuss', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Mistborn', 'Brandon Sanderson', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Caminho dos Reis', 'Brandon Sanderson', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Duna', 'Frank Herbert', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Messias de Duna', 'Frank Herbert', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Fundação', 'Isaac Asimov', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Eu, Robô', 'Isaac Asimov', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Neuromancer', 'William Gibson', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Snow Crash', 'Neal Stephenson', 'pt', 'CLASSIC', NOW(), NOW()),
    ('1984', 'George Orwell', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Admirável Mundo Novo', 'Aldous Huxley', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Fahrenheit 451', 'Ray Bradbury', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Jogos Vorazes', 'Suzanne Collins', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Em Chamas', 'Suzanne Collins', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Esperança', 'Suzanne Collins', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Razão e Sensibilidade', 'Jane Austen', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Jane Eyre', 'Charlotte Brontë', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Morro dos Ventos Uivantes', 'Emily Brontë', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Como Eu Era Antes de Você', 'Jojo Moyes', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('É Assim que Acaba', 'Colleen Hoover', 'pt', 'TRENDING', NOW(), NOW()),
    ('Todas as Suas Imperfeições', 'Colleen Hoover', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Hipótese do Amor', 'Ali Hazelwood', 'pt', 'TRENDING', NOW(), NOW()),
    ('A Canção de Aquiles', 'Madeline Miller', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Vermelho, Branco e Sangue Azul', 'Casey McQuiston', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Heartstopper', 'Alice Oseman', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Loveless', 'Alice Oseman', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Aristóteles e Dante Descobrem os Segredos do Universo', 'Benjamin Alire Sáenz', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Iluminado', 'Stephen King', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Misery', 'Stephen King', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Carrie', 'Stephen King', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Doutor Sono', 'Stephen King', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Drácula', 'Bram Stoker', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Frankenstein', 'Mary Shelley', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Assassinato no Expresso do Oriente', 'Agatha Christie', 'pt', 'CLASSIC', NOW(), NOW()),
    ('E Não Sobrou Nenhum', 'Agatha Christie', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Caso dos Dez Negrinhos', 'Agatha Christie', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Código Da Vinci', 'Dan Brown', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Anjos e Demônios', 'Dan Brown', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Garota Exemplar', 'Gillian Flynn', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Garota no Trem', 'Paula Hawkins', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Sapiens', 'Yuval Noah Harari', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Homo Deus', 'Yuval Noah Harari', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('21 Lições para o Século 21', 'Yuval Noah Harari', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Poder do Hábito', 'Charles Duhigg', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Essencialismo', 'Greg McKeown', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Pai Rico Pai Pobre', 'Robert Kiyosaki', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Psicologia Financeira', 'Morgan Housel', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Quem Pensa Enriquece', 'Napoleon Hill', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Meditações', 'Marco Aurélio', 'pt', 'CLASSIC', NOW(), NOW()),
    ('A República', 'Platão', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Assim Falou Zaratustra', 'Friedrich Nietzsche', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Crime e Castigo', 'Fiódor Dostoiévski', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Os Irmãos Karamázov', 'Fiódor Dostoiévski', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Dom Quixote', 'Miguel de Cervantes', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Os Miseráveis', 'Victor Hugo', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Guerra e Paz', 'Liev Tolstói', 'pt', 'CLASSIC', NOW(), NOW()),
    ('A Revolução dos Bichos', 'George Orwell', 'pt', 'CLASSIC', NOW(), NOW()),
    ('A Metamorfose', 'Franz Kafka', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Capitães da Areia', 'Jorge Amado', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Vidas Secas', 'Graciliano Ramos', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Memórias Póstumas de Brás Cubas', 'Machado de Assis', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Berserk Vol. 1', 'Kentaro Miura', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('One Piece Vol. 1', 'Eiichiro Oda', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Naruto Vol. 1', 'Masashi Kishimoto', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Attack on Titan Vol. 1', 'Hajime Isayama', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Death Note Vol. 1', 'Tsugumi Ohba', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Chainsaw Man Vol. 1', 'Tatsuki Fujimoto', 'pt', 'TRENDING', NOW(), NOW()),
    ('Jujutsu Kaisen Vol. 1', 'Gege Akutami', 'pt', 'TRENDING', NOW(), NOW());

INSERT INTO book_catalog_genre (book_catalog_id, genre)
VALUES
    ((SELECT id FROM book_catalog WHERE title = 'Dom Casmurro'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'O Pequeno Príncipe'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Pequeno Príncipe'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e a Pedra Filosofal'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e a Pedra Filosofal'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'A Biblioteca da Meia-Noite'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'A Biblioteca da Meia-Noite'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'A Empregada'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'A Empregada'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Verity'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Verity'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'It: A Coisa'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'It: A Coisa'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Orgulho e Preconceito'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Orgulho e Preconceito'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Hábitos Atômicos'), 'SELF_HELP'),
    ((SELECT id FROM book_catalog WHERE title = 'Hábitos Atômicos'), 'PRODUCTIVITY'),
    ((SELECT id FROM book_catalog WHERE title = 'A Hora da Estrela'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'O Senhor dos Anéis: A Sociedade do Anel'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Senhor dos Anéis: A Sociedade do Anel'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Hobbit'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Hobbit'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'As Duas Torres'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'As Duas Torres'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Retorno do Rei'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Retorno do Rei'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e a Câmara Secreta'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e a Câmara Secreta'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e o Prisioneiro de Azkaban'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e o Prisioneiro de Azkaban'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e o Cálice de Fogo'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e o Cálice de Fogo'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Percy Jackson e o Mar de Monstros'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Percy Jackson e o Mar de Monstros'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Nome do Vento'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Nome do Vento'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Temor do Sábio'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Temor do Sábio'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Mistborn'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Mistborn'), 'ACTION'),
    ((SELECT id FROM book_catalog WHERE title = 'O Caminho dos Reis'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Caminho dos Reis'), 'ACTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Duna'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Duna'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Messias de Duna'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Messias de Duna'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Fundação'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Eu, Robô'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Neuromancer'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Snow Crash'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Snow Crash'), 'ACTION'),
    ((SELECT id FROM book_catalog WHERE title = '1984'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = '1984'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Admirável Mundo Novo'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Admirável Mundo Novo'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Fahrenheit 451'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Fahrenheit 451'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Jogos Vorazes'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Jogos Vorazes'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'Em Chamas'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Em Chamas'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'A Esperança'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'A Esperança'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'Razão e Sensibilidade'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Razão e Sensibilidade'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Jane Eyre'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Jane Eyre'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Morro dos Ventos Uivantes'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Morro dos Ventos Uivantes'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Como Eu Era Antes de Você'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Como Eu Era Antes de Você'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'É Assim que Acaba'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'É Assim que Acaba'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Todas as Suas Imperfeições'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Todas as Suas Imperfeições'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'A Hipótese do Amor'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'A Canção de Aquiles'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'A Canção de Aquiles'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Vermelho, Branco e Sangue Azul'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Vermelho, Branco e Sangue Azul'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Heartstopper'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Heartstopper'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'Loveless'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Loveless'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'Aristóteles e Dante Descobrem os Segredos do Universo'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Aristóteles e Dante Descobrem os Segredos do Universo'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'O Iluminado'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Misery'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Misery'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'Carrie'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Doutor Sono'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Drácula'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Frankenstein'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Frankenstein'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Assassinato no Expresso do Oriente'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Assassinato no Expresso do Oriente'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'E Não Sobrou Nenhum'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'E Não Sobrou Nenhum'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'O Caso dos Dez Negrinhos'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Caso dos Dez Negrinhos'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'Código Da Vinci'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'Código Da Vinci'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Anjos e Demônios'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'Anjos e Demônios'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Garota Exemplar'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'Garota Exemplar'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'A Garota no Trem'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'A Garota no Trem'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'Sapiens'), 'HISTORY'),
    ((SELECT id FROM book_catalog WHERE title = 'Sapiens'), 'SCIENCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Homo Deus'), 'SCIENCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Homo Deus'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = '21 Lições para o Século 21'), 'POLITICS'),
    ((SELECT id FROM book_catalog WHERE title = '21 Lições para o Século 21'), 'SCIENCE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Poder do Hábito'), 'SELF_HELP'),
    ((SELECT id FROM book_catalog WHERE title = 'O Poder do Hábito'), 'PSYCHOLOGY'),
    ((SELECT id FROM book_catalog WHERE title = 'Essencialismo'), 'PRODUCTIVITY'),
    ((SELECT id FROM book_catalog WHERE title = 'Essencialismo'), 'BUSINESS'),
    ((SELECT id FROM book_catalog WHERE title = 'Pai Rico Pai Pobre'), 'FINANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Pai Rico Pai Pobre'), 'BUSINESS'),
    ((SELECT id FROM book_catalog WHERE title = 'A Psicologia Financeira'), 'FINANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'A Psicologia Financeira'), 'PSYCHOLOGY'),
    ((SELECT id FROM book_catalog WHERE title = 'Quem Pensa Enriquece'), 'BUSINESS'),
    ((SELECT id FROM book_catalog WHERE title = 'Quem Pensa Enriquece'), 'SELF_HELP'),
    ((SELECT id FROM book_catalog WHERE title = 'Meditações'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = 'A República'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = 'A República'), 'POLITICS'),
    ((SELECT id FROM book_catalog WHERE title = 'Assim Falou Zaratustra'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = 'Crime e Castigo'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Crime e Castigo'), 'CLASSIC'),
    ((SELECT id FROM book_catalog WHERE title = 'Os Irmãos Karamázov'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Os Irmãos Karamázov'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = 'Dom Quixote'), 'CLASSIC'),
    ((SELECT id FROM book_catalog WHERE title = 'Dom Quixote'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Os Miseráveis'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Os Miseráveis'), 'HISTORICAL_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Guerra e Paz'), 'HISTORICAL_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Guerra e Paz'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'A Revolução dos Bichos'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'A Revolução dos Bichos'), 'POLITICS'),
    ((SELECT id FROM book_catalog WHERE title = 'A Metamorfose'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Capitães da Areia'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Vidas Secas'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Memórias Póstumas de Brás Cubas'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Berserk Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Berserk Vol. 1'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'One Piece Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'One Piece Vol. 1'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Naruto Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Naruto Vol. 1'), 'ACTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Attack on Titan Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Attack on Titan Vol. 1'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Death Note Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Death Note Vol. 1'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Chainsaw Man Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Chainsaw Man Vol. 1'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Jujutsu Kaisen Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Jujutsu Kaisen Vol. 1'), 'ACTION');
