-- Catálogo local de referência para recomendações personalizadas.
-- Padrão por mídia: tabela de itens + tabela de gêneros + editorial_category (TRENDING, BESTSELLER, CLASSIC).

CREATE TABLE IF NOT EXISTS movie_catalog_genre
(
    movie_catalog_id BIGINT      NOT NULL,
    genre            VARCHAR(50) NOT NULL,
    CONSTRAINT fk_movie_catalog_genre_movie FOREIGN KEY (movie_catalog_id) REFERENCES movie_catalog (id)
);

CREATE TABLE IF NOT EXISTS series_catalog_genre
(
    series_catalog_id BIGINT      NOT NULL,
    genre             VARCHAR(50) NOT NULL,
    CONSTRAINT fk_series_catalog_genre_series FOREIGN KEY (series_catalog_id) REFERENCES series_catalog (id)
);

CREATE TABLE IF NOT EXISTS game_catalog_genre
(
    game_catalog_id BIGINT      NOT NULL,
    genre           VARCHAR(50) NOT NULL,
    CONSTRAINT fk_game_catalog_genre_game FOREIGN KEY (game_catalog_id) REFERENCES game_catalog (id)
);

ALTER TABLE game_catalog ADD COLUMN IF NOT EXISTS editorial_category VARCHAR(20);

CREATE INDEX IF NOT EXISTS idx_movie_catalog_genre_name ON movie_catalog_genre (genre);
CREATE INDEX IF NOT EXISTS idx_series_catalog_genre_name ON series_catalog_genre (genre);
CREATE INDEX IF NOT EXISTS idx_game_catalog_genre_name ON game_catalog_genre (genre);
CREATE INDEX IF NOT EXISTS idx_game_catalog_editorial_category ON game_catalog (editorial_category);

-- Livros

INSERT INTO book_catalog (title, author, language, editorial_category, created_at, updated_at)
VALUES
    ('Dom Casmurro', 'Machado de Assis', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Harry Potter e a Pedra Filosofal', 'J. K. Rowling', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Biblioteca da Meia-Noite', 'Matt Haig', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Empregada', 'Freida McFadden', 'pt', 'TRENDING', NOW(), NOW()),
    ('Verity', 'Colleen Hoover', 'pt', 'TRENDING', NOW(), NOW()),
    ('It: A Coisa', 'Stephen King', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Orgulho e Preconceito', 'Jane Austen', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Hábitos Atômicos', 'James Clear', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Hora da Estrela', 'Clarice Lispector', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Senhor dos Anéis: A Sociedade do Anel', 'J. R. R. Tolkien', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Hobbit', 'J. R. R. Tolkien', 'pt', 'CLASSIC', NOW(), NOW()),
    ('As Duas Torres', 'J. R. R. Tolkien', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Retorno do Rei', 'J. R. R. Tolkien', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Harry Potter e a Câmara Secreta', 'J. K. Rowling', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Harry Potter e o Prisioneiro de Azkaban', 'J. K. Rowling', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Harry Potter e o Cálice de Fogo', 'J. K. Rowling', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Percy Jackson e o Mar de Monstros', 'Rick Riordan', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Nome do Vento', 'Patrick Rothfuss', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Temor do Sábio', 'Patrick Rothfuss', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Mistborn', 'Brandon Sanderson', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Caminho dos Reis', 'Brandon Sanderson', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Duna', 'Frank Herbert', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Messias de Duna', 'Frank Herbert', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Fundação', 'Isaac Asimov', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Eu, Robô', 'Isaac Asimov', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Neuromancer', 'William Gibson', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Snow Crash', 'Neal Stephenson', 'pt', 'CLASSIC', NOW(), NOW()),
    ('1984', 'George Orwell', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Admirável Mundo Novo', 'Aldous Huxley', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Fahrenheit 451', 'Ray Bradbury', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Jogos Vorazes', 'Suzanne Collins', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Em Chamas', 'Suzanne Collins', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Esperança', 'Suzanne Collins', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Razão e Sensibilidade', 'Jane Austen', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Jane Eyre', 'Charlotte Brontë', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Morro dos Ventos Uivantes', 'Emily Brontë', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Como Eu Era Antes de Você', 'Jojo Moyes', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('É Assim que Acaba', 'Colleen Hoover', 'pt', 'TRENDING', NOW(), NOW()),
    ('Todas as Suas Imperfeições', 'Colleen Hoover', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Hipótese do Amor', 'Ali Hazelwood', 'pt', 'TRENDING', NOW(), NOW()),
    ('A Canção de Aquiles', 'Madeline Miller', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Vermelho, Branco e Sangue Azul', 'Casey McQuiston', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Heartstopper', 'Alice Oseman', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Loveless', 'Alice Oseman', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Aristóteles e Dante Descobrem os Segredos do Universo', 'Benjamin Alire Sáenz', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Iluminado', 'Stephen King', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Misery', 'Stephen King', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Carrie', 'Stephen King', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Doutor Sono', 'Stephen King', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Drácula', 'Bram Stoker', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Frankenstein', 'Mary Shelley', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Assassinato no Expresso do Oriente', 'Agatha Christie', 'pt', 'CLASSIC', NOW(), NOW()),
    ('E Não Sobrou Nenhum', 'Agatha Christie', 'pt', 'CLASSIC', NOW(), NOW()),
    ('O Caso dos Dez Negrinhos', 'Agatha Christie', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Código Da Vinci', 'Dan Brown', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Anjos e Demônios', 'Dan Brown', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Garota Exemplar', 'Gillian Flynn', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Garota no Trem', 'Paula Hawkins', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Sapiens', 'Yuval Noah Harari', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Homo Deus', 'Yuval Noah Harari', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('21 Lições para o Século 21', 'Yuval Noah Harari', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('O Poder do Hábito', 'Charles Duhigg', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Essencialismo', 'Greg McKeown', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Pai Rico Pai Pobre', 'Robert Kiyosaki', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('A Psicologia Financeira', 'Morgan Housel', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Quem Pensa Enriquece', 'Napoleon Hill', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Meditações', 'Marco Aurélio', 'pt', 'CLASSIC', NOW(), NOW()),
    ('A República', 'Platão', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Assim Falou Zaratustra', 'Friedrich Nietzsche', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Crime e Castigo', 'Fiódor Dostoiévski', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Os Irmãos Karamázov', 'Fiódor Dostoiévski', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Dom Quixote', 'Miguel de Cervantes', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Os Miseráveis', 'Victor Hugo', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Guerra e Paz', 'Liev Tolstói', 'pt', 'CLASSIC', NOW(), NOW()),
    ('A Revolução dos Bichos', 'George Orwell', 'pt', 'CLASSIC', NOW(), NOW()),
    ('A Metamorfose', 'Franz Kafka', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Capitães da Areia', 'Jorge Amado', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Vidas Secas', 'Graciliano Ramos', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Memórias Póstumas de Brás Cubas', 'Machado de Assis', 'pt', 'CLASSIC', NOW(), NOW()),
    ('Berserk Vol. 1', 'Kentaro Miura', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('One Piece Vol. 1', 'Eiichiro Oda', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Naruto Vol. 1', 'Masashi Kishimoto', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Attack on Titan Vol. 1', 'Hajime Isayama', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Death Note Vol. 1', 'Tsugumi Ohba', 'pt', 'BESTSELLER', NOW(), NOW()),
    ('Chainsaw Man Vol. 1', 'Tatsuki Fujimoto', 'pt', 'TRENDING', NOW(), NOW()),
    ('Jujutsu Kaisen Vol. 1', 'Gege Akutami', 'pt', 'TRENDING', NOW(), NOW());

INSERT INTO book_catalog_genre (book_catalog_id, genre)
VALUES
    ((SELECT id FROM book_catalog WHERE title = 'Dom Casmurro'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'O Pequeno Príncipe'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Pequeno Príncipe'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e a Pedra Filosofal'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e a Pedra Filosofal'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'A Biblioteca da Meia-Noite'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'A Biblioteca da Meia-Noite'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'A Empregada'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'A Empregada'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Verity'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Verity'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'It: A Coisa'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'It: A Coisa'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Orgulho e Preconceito'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Orgulho e Preconceito'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Hábitos Atômicos'), 'SELF_HELP'),
    ((SELECT id FROM book_catalog WHERE title = 'Hábitos Atômicos'), 'PRODUCTIVITY'),
    ((SELECT id FROM book_catalog WHERE title = 'A Hora da Estrela'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'O Senhor dos Anéis: A Sociedade do Anel'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Senhor dos Anéis: A Sociedade do Anel'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Hobbit'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Hobbit'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'As Duas Torres'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'As Duas Torres'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Retorno do Rei'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Retorno do Rei'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e a Câmara Secreta'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e a Câmara Secreta'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e o Prisioneiro de Azkaban'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e o Prisioneiro de Azkaban'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e o Cálice de Fogo'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Harry Potter e o Cálice de Fogo'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Percy Jackson e o Mar de Monstros'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Percy Jackson e o Mar de Monstros'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Nome do Vento'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Nome do Vento'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Temor do Sábio'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Temor do Sábio'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Mistborn'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'Mistborn'), 'ACTION'),
    ((SELECT id FROM book_catalog WHERE title = 'O Caminho dos Reis'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Caminho dos Reis'), 'ACTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Duna'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Duna'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Messias de Duna'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Messias de Duna'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Fundação'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Eu, Robô'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Neuromancer'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Snow Crash'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Snow Crash'), 'ACTION'),
    ((SELECT id FROM book_catalog WHERE title = '1984'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = '1984'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Admirável Mundo Novo'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Admirável Mundo Novo'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Fahrenheit 451'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Fahrenheit 451'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Jogos Vorazes'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Jogos Vorazes'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'Em Chamas'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'Em Chamas'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'A Esperança'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'A Esperança'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'Razão e Sensibilidade'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Razão e Sensibilidade'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Jane Eyre'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Jane Eyre'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Morro dos Ventos Uivantes'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Morro dos Ventos Uivantes'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Como Eu Era Antes de Você'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Como Eu Era Antes de Você'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'É Assim que Acaba'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'É Assim que Acaba'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Todas as Suas Imperfeições'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Todas as Suas Imperfeições'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'A Hipótese do Amor'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'A Canção de Aquiles'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'A Canção de Aquiles'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Vermelho, Branco e Sangue Azul'), 'ROMANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Vermelho, Branco e Sangue Azul'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Heartstopper'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Heartstopper'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'Loveless'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Loveless'), 'YOUNG_ADULT'),
    ((SELECT id FROM book_catalog WHERE title = 'Aristóteles e Dante Descobrem os Segredos do Universo'), 'LGBTQIA_PLUS'),
    ((SELECT id FROM book_catalog WHERE title = 'Aristóteles e Dante Descobrem os Segredos do Universo'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'O Iluminado'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Misery'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Misery'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'Carrie'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Doutor Sono'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Drácula'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Frankenstein'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Frankenstein'), 'SCIENCE_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Assassinato no Expresso do Oriente'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Assassinato no Expresso do Oriente'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'E Não Sobrou Nenhum'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'E Não Sobrou Nenhum'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'O Caso dos Dez Negrinhos'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'O Caso dos Dez Negrinhos'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'Código Da Vinci'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'Código Da Vinci'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Anjos e Demônios'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'Anjos e Demônios'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Garota Exemplar'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'Garota Exemplar'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'A Garota no Trem'), 'THRILLER'),
    ((SELECT id FROM book_catalog WHERE title = 'A Garota no Trem'), 'CRIME'),
    ((SELECT id FROM book_catalog WHERE title = 'Sapiens'), 'HISTORY'),
    ((SELECT id FROM book_catalog WHERE title = 'Sapiens'), 'SCIENCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Homo Deus'), 'SCIENCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Homo Deus'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = '21 Lições para o Século 21'), 'POLITICS'),
    ((SELECT id FROM book_catalog WHERE title = '21 Lições para o Século 21'), 'SCIENCE'),
    ((SELECT id FROM book_catalog WHERE title = 'O Poder do Hábito'), 'SELF_HELP'),
    ((SELECT id FROM book_catalog WHERE title = 'O Poder do Hábito'), 'PSYCHOLOGY'),
    ((SELECT id FROM book_catalog WHERE title = 'Essencialismo'), 'PRODUCTIVITY'),
    ((SELECT id FROM book_catalog WHERE title = 'Essencialismo'), 'BUSINESS'),
    ((SELECT id FROM book_catalog WHERE title = 'Pai Rico Pai Pobre'), 'FINANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'Pai Rico Pai Pobre'), 'BUSINESS'),
    ((SELECT id FROM book_catalog WHERE title = 'A Psicologia Financeira'), 'FINANCE'),
    ((SELECT id FROM book_catalog WHERE title = 'A Psicologia Financeira'), 'PSYCHOLOGY'),
    ((SELECT id FROM book_catalog WHERE title = 'Quem Pensa Enriquece'), 'BUSINESS'),
    ((SELECT id FROM book_catalog WHERE title = 'Quem Pensa Enriquece'), 'SELF_HELP'),
    ((SELECT id FROM book_catalog WHERE title = 'Meditações'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = 'A República'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = 'A República'), 'POLITICS'),
    ((SELECT id FROM book_catalog WHERE title = 'Assim Falou Zaratustra'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = 'Crime e Castigo'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Crime e Castigo'), 'CLASSIC'),
    ((SELECT id FROM book_catalog WHERE title = 'Os Irmãos Karamázov'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Os Irmãos Karamázov'), 'PHILOSOPHY'),
    ((SELECT id FROM book_catalog WHERE title = 'Dom Quixote'), 'CLASSIC'),
    ((SELECT id FROM book_catalog WHERE title = 'Dom Quixote'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Os Miseráveis'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Os Miseráveis'), 'HISTORICAL_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Guerra e Paz'), 'HISTORICAL_FICTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Guerra e Paz'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'A Revolução dos Bichos'), 'DYSTOPIAN'),
    ((SELECT id FROM book_catalog WHERE title = 'A Revolução dos Bichos'), 'POLITICS'),
    ((SELECT id FROM book_catalog WHERE title = 'A Metamorfose'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Capitães da Areia'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Vidas Secas'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Memórias Póstumas de Brás Cubas'), 'DRAMA'),
    ((SELECT id FROM book_catalog WHERE title = 'Berserk Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Berserk Vol. 1'), 'FANTASY'),
    ((SELECT id FROM book_catalog WHERE title = 'One Piece Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'One Piece Vol. 1'), 'ADVENTURE'),
    ((SELECT id FROM book_catalog WHERE title = 'Naruto Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Naruto Vol. 1'), 'ACTION'),
    ((SELECT id FROM book_catalog WHERE title = 'Attack on Titan Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Attack on Titan Vol. 1'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Death Note Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Death Note Vol. 1'), 'MYSTERY'),
    ((SELECT id FROM book_catalog WHERE title = 'Chainsaw Man Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Chainsaw Man Vol. 1'), 'HORROR'),
    ((SELECT id FROM book_catalog WHERE title = 'Jujutsu Kaisen Vol. 1'), 'MANGA'),
    ((SELECT id FROM book_catalog WHERE title = 'Jujutsu Kaisen Vol. 1'), 'ACTION');

-- Filmes
INSERT INTO movie_catalog (tmdb_id, title, editorial_category, director, created_at, updated_at)
VALUES
    (980001, 'Duna: Parte Dois', 'TRENDING', 'Denis Villeneuve', NOW(), NOW()),
    (980002, 'Oppenheimer', 'TRENDING', 'Christopher Nolan', NOW(), NOW()),
    (980003, 'Barbie', 'TRENDING', 'Greta Gerwig', NOW(), NOW()),
    (980004, 'Flow', 'TRENDING', 'Laura Wadell', NOW(), NOW()),
    (980005, 'Deadpool & Wolverine', 'TRENDING', 'Shawn Levy', NOW(), NOW()),
    (980006, 'Inside Out 2', 'TRENDING', 'Kelsey Mann', NOW(), NOW()),
    (980007, 'Vingadores: Ultimato', 'BESTSELLER', 'Anthony Russo', NOW(), NOW()),
    (980008, 'Avatar', 'BESTSELLER', 'James Cameron', NOW(), NOW()),
    (980009, 'Titanic', 'BESTSELLER', 'James Cameron', NOW(), NOW()),
    (980010, 'O Rei Leão', 'BESTSELLER', 'Roger Allers', NOW(), NOW()),
    (980011, 'Star Wars', 'BESTSELLER', 'George Lucas', NOW(), NOW()),
    (980012, 'Homem-Aranha: Sem Volta para Casa', 'BESTSELLER', 'Jon Watts', NOW(), NOW()),
    (980013, 'O Poderoso Chefão', 'CLASSIC', 'Francis Ford Coppola', NOW(), NOW()),
    (980014, 'Pulp Fiction', 'CLASSIC', 'Quentin Tarantino', NOW(), NOW()),
    (980015, 'Matrix', 'CLASSIC', 'Lana Wachowski', NOW(), NOW()),
    (980016, 'Clube da Luta', 'CLASSIC', 'David Fincher', NOW(), NOW()),
    (980017, 'E.T.', 'CLASSIC', 'Steven Spielberg', NOW(), NOW()),
    (980018, 'De Volta para o Futuro', 'CLASSIC', 'Robert Zemeckis', NOW(), NOW());

INSERT INTO movie_catalog_genre (movie_catalog_id, genre)
VALUES
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980001), 'SCI_FI'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980001), 'ACTION'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980002), 'DRAMA'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980002), 'THRILLER'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980003), 'COMEDY'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980004), 'DRAMA'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980005), 'ACTION'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980005), 'COMEDY'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980006), 'COMEDY'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980006), 'DRAMA'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980007), 'ACTION'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980007), 'SCI_FI'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980008), 'SCI_FI'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980008), 'ACTION'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980009), 'DRAMA'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980009), 'ROMANCE'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980010), 'DRAMA'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980011), 'SCI_FI'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980011), 'ACTION'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980012), 'ACTION'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980012), 'SCI_FI'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980013), 'DRAMA'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980013), 'THRILLER'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980014), 'THRILLER'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980014), 'DRAMA'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980015), 'SCI_FI'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980015), 'ACTION'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980016), 'THRILLER'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980016), 'DRAMA'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980017), 'SCI_FI'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980017), 'DRAMA'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980018), 'SCI_FI'),
    ((SELECT id FROM movie_catalog WHERE tmdb_id = 980018), 'COMEDY');

-- Séries
INSERT INTO series_catalog (tmdb_id, name, editorial_category, creator, created_at, updated_at)
VALUES
    (970001, 'The Last of Us', 'TRENDING', 'Craig Mazin', NOW(), NOW()),
    (970002, 'Fallout', 'TRENDING', 'Jonathan Nolan', NOW(), NOW()),
    (970003, 'Shogun', 'TRENDING', 'Rachel Kondo', NOW(), NOW()),
    (970004, 'House of the Dragon', 'TRENDING', 'Ryan Condal', NOW(), NOW()),
    (970005, 'Wednesday', 'TRENDING', 'Alfred Gough', NOW(), NOW()),
    (970006, 'The Penguin', 'TRENDING', 'Lauren LeFranc', NOW(), NOW()),
    (970007, 'Breaking Bad', 'BESTSELLER', 'Vince Gilligan', NOW(), NOW()),
    (970008, 'Game of Thrones', 'BESTSELLER', 'David Benioff', NOW(), NOW()),
    (970009, 'Stranger Things', 'BESTSELLER', 'Matt Duffer', NOW(), NOW()),
    (970010, 'The Witcher', 'BESTSELLER', 'Lauren Schmidt', NOW(), NOW()),
    (970011, 'The Mandalorian', 'BESTSELLER', 'Jon Favreau', NOW(), NOW()),
    (970012, 'Arcane', 'BESTSELLER', 'Christian Linke', NOW(), NOW()),
    (970013, 'Friends', 'CLASSIC', 'David Crane', NOW(), NOW()),
    (970014, 'The Office', 'CLASSIC', 'Greg Daniels', NOW(), NOW()),
    (970015, 'Seinfeld', 'CLASSIC', 'Larry David', NOW(), NOW()),
    (970016, 'The Sopranos', 'CLASSIC', 'David Chase', NOW(), NOW()),
    (970017, 'Lost', 'CLASSIC', 'J.J. Abrams', NOW(), NOW()),
    (970018, 'Doctor Who', 'CLASSIC', 'Sydney Newman', NOW(), NOW());

INSERT INTO series_catalog_genre (series_catalog_id, genre)
VALUES
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970001), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970001), 'SCI_FI'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970002), 'SCI_FI'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970002), 'ACTION'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970003), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970003), 'ACTION'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970004), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970004), 'ACTION'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970005), 'COMEDY'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970005), 'HORROR'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970006), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970006), 'THRILLER'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970007), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970007), 'THRILLER'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970008), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970008), 'ACTION'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970009), 'SCI_FI'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970009), 'HORROR'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970010), 'ACTION'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970010), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970011), 'SCI_FI'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970011), 'ACTION'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970012), 'ACTION'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970012), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970013), 'COMEDY'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970013), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970014), 'COMEDY'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970015), 'COMEDY'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970016), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970016), 'THRILLER'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970017), 'DRAMA'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970017), 'SCI_FI'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970018), 'SCI_FI'),
    ((SELECT id FROM series_catalog WHERE tmdb_id = 970018), 'DRAMA');

-- Jogos
INSERT INTO game_catalog (rawg_id, name, editorial_category)
VALUES
    (990001, 'Palworld', 'TRENDING'),
    (990002, 'Helldivers 2', 'TRENDING'),
    (990003, 'Black Myth: Wukong', 'TRENDING'),
    (990004, 'Marvel Rivals', 'TRENDING'),
    (990005, 'Dragon''s Dogma 2', 'TRENDING'),
    (990006, 'Balatro', 'TRENDING'),
    (990007, 'Elden Ring', 'BESTSELLER'),
    (990008, 'Grand Theft Auto V', 'BESTSELLER'),
    (990009, 'Minecraft', 'BESTSELLER'),
    (990010, 'Counter-Strike 2', 'BESTSELLER'),
    (990011, 'Red Dead Redemption 2', 'BESTSELLER'),
    (990012, 'Hogwarts Legacy', 'BESTSELLER'),
    (990013, 'The Witcher 3: Wild Hunt', 'CLASSIC'),
    (990014, 'Half-Life 2', 'CLASSIC'),
    (990015, 'Portal 2', 'CLASSIC'),
    (990016, 'The Elder Scrolls V: Skyrim', 'CLASSIC'),
    (990017, 'Dark Souls', 'CLASSIC'),
    (990018, 'Halo: Combat Evolved', 'CLASSIC');

INSERT INTO game_catalog_genre (game_catalog_id, genre)
VALUES
    ((SELECT id FROM game_catalog WHERE rawg_id = 990001), 'ADVENTURE'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990001), 'SANDBOX'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990002), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990002), 'COOP'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990003), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990003), 'RPG'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990004), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990004), 'MOBA'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990005), 'RPG'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990005), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990006), 'PUZZLE'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990007), 'RPG'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990007), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990008), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990008), 'ADVENTURE'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990009), 'SANDBOX'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990009), 'ADVENTURE'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990010), 'FPS'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990010), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990011), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990011), 'ADVENTURE'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990012), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990012), 'RPG'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990013), 'RPG'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990013), 'ADVENTURE'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990014), 'FPS'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990014), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990015), 'PUZZLE'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990015), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990016), 'RPG'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990016), 'ADVENTURE'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990017), 'RPG'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990017), 'ACTION'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990018), 'FPS'),
    ((SELECT id FROM game_catalog WHERE rawg_id = 990018), 'ACTION');
